version: '3'

services:
  nginx:
    image: owasp/modsecurity-crs:nginx
    environment:
      BACKEND: http://rails:3000
    ports:
      - "80:80"
    depends_on:
      - rails

  rails:
    container_name: sqli_app
    build:
      context: .
      dockerfile: ./dockers/rails/Dockerfile
    image: sqli-rails:3.2
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    environment:
      DB_HOST: db
      DB_USERNAME: sqli_app_user
      DB_PASSWORD: sqli_app_password
    command: >
      /usr/local/bin/wait-for-it.sh db:3306 --timeout=30 --
      bash -c "bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    container_name: sqli_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: r
      MYSQL_USER: sqli_app_user
      MYSQL_PASSWORD: sqli_app_password
    volumes:
      - db_data:/var/lib/mysql
      - ./dockers/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  redis:
    container_name: sqli_redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  bundle_data:
  db_data:
  redis_data:
